//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lochat.Shared {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lochat.Shared.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command {0} not found. Use &quot;lochat help&quot; for get list of commands..
        /// </summary>
        public static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installed version: {0}.{1}.{2} (rev {3})..
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your date format is: {0}. To change it, use: &quot;lochat settings --dateFormat (your_new_date_format)&quot;.
        /// </summary>
        public static string DateFormatValue {
            get {
                return ResourceManager.GetString("DateFormatValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your default server is: {0}. To change it, use: &quot;lochat settings --defaultServer (your_new_server_name)&quot;.
        /// </summary>
        public static string DefaultServerValue {
            get {
                return ResourceManager.GetString("DefaultServerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter server name (leave it empty if you want to connect this computer):  .
        /// </summary>
        public static string EnterDefaultServer {
            get {
                return ResourceManager.GetString("EnterDefaultServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your message: .
        /// </summary>
        public static string EnterYourMessage {
            get {
                return ResourceManager.GetString("EnterYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your name: .
        /// </summary>
        public static string EnterYourName {
            get {
                return ResourceManager.GetString("EnterYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your username: .
        /// </summary>
        public static string EnterYourUsername {
            get {
                return ResourceManager.GetString("EnterYourUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server {0} not initialized. Are you forgot &quot;lochat init&quot;?.
        /// </summary>
        public static string ErrorConnectingFolderNotFound {
            get {
                return ResourceManager.GetString("ErrorConnectingFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First setup ended. Trying to connect {0}....
        /// </summary>
        public static string FirstSetupEnded {
            get {
                return ResourceManager.GetString("FirstSetupEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} ({1}) [{2}]: {3}.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your name is {0}. To change it use &quot;lochat settings --name (your_new_name)&quot;.
        /// </summary>
        public static string NameValue {
            get {
                return ResourceManager.GetString("NameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your date format set to: {0}..
        /// </summary>
        public static string SetDateFormatValue {
            get {
                return ResourceManager.GetString("SetDateFormatValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your default server set to: {0}..
        /// </summary>
        public static string SetDefaultServerValue {
            get {
                return ResourceManager.GetString("SetDefaultServerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your name set to: {0}..
        /// </summary>
        public static string SetNameValue {
            get {
                return ResourceManager.GetString("SetNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your username set to: {0}..
        /// </summary>
        public static string SetUsernameValue {
            get {
                return ResourceManager.GetString("SetUsernameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are connected to {0}. Use &quot;lochat join&quot; for join chat..
        /// </summary>
        public static string SuccessConnecting {
            get {
                return ResourceManager.GetString("SuccessConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are entered invalid count of arguments. Use &quot;lochat help {0}&quot; for getting help..
        /// </summary>
        public static string UnsupportedArgumentsCount {
            get {
                return ResourceManager.GetString("UnsupportedArgumentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your username is: {0}. To change it, use: &quot;lochat settings --username (your_new_username)&quot;.
        /// </summary>
        public static string UsernameValue {
            get {
                return ResourceManager.GetString("UsernameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot to get your version. Please report this bug to https://github.com/alekami649/lochat/issues..
        /// </summary>
        public static string VersionError {
            get {
                return ResourceManager.GetString("VersionError", resourceCulture);
            }
        }
    }
}
